[build]
    functions = "functions"

[context.production.environment]
    email = "erikhvamdev@gmail.com"
    password = "Danebu123"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200